# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddd9feab3940823c48eb6aa47ac1560c273e7be698e922d4dc474bbd8b1d0139b33790e306a5ffea201f5e187471848ef8f6463395ac919730579c8cb6242901

test:
  secret_key_base: ca3e71eafa3e97faa793fff09f1b245c292fe03fb26356bab6c63c09885f32c335a1dabd31c4ac8a8aef00f9345420b5222eb1933ba467e2310bebf0579b2e75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
